// Mocks generated by Mockito 5.4.6 from annotations
// in spend_app/test/features/admin_panel/admin_panel_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:spend_app/src/core/models/article_model.dart' as _i4;
import 'package:spend_app/src/core/models/goal_model.dart' as _i3;
import 'package:spend_app/src/core/services/goal_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GoalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoalService extends _i1.Mock implements _i2.GoalService {
  MockGoalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Goal> getGoals() =>
      (super.noSuchMethod(
            Invocation.method(#getGoals, []),
            returnValue: <_i3.Goal>[],
          )
          as List<_i3.Goal>);

  @override
  _i3.Goal? getGoalById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getGoalById, [id])) as _i3.Goal?);

  @override
  void addGoal(_i3.Goal? newGoal) => super.noSuchMethod(
    Invocation.method(#addGoal, [newGoal]),
    returnValueForMissingStub: null,
  );

  @override
  void updateGoal(_i3.Goal? updatedGoal) => super.noSuchMethod(
    Invocation.method(#updateGoal, [updatedGoal]),
    returnValueForMissingStub: null,
  );

  @override
  void deleteGoal(String? id) => super.noSuchMethod(
    Invocation.method(#deleteGoal, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void highlightGoal(String? id) => super.noSuchMethod(
    Invocation.method(#highlightGoal, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void addMoneyToHighlightedGoal(double? amount) => super.noSuchMethod(
    Invocation.method(#addMoneyToHighlightedGoal, [amount]),
    returnValueForMissingStub: null,
  );

  @override
  void resetHighlightedGoalCurrentAmount() => super.noSuchMethod(
    Invocation.method(#resetHighlightedGoalCurrentAmount, []),
    returnValueForMissingStub: null,
  );

  @override
  void addArticleToGoal(String? goalId, _i4.Article? article) =>
      super.noSuchMethod(
        Invocation.method(#addArticleToGoal, [goalId, article]),
        returnValueForMissingStub: null,
      );

  @override
  void removeArticleFromGoal(String? goalId, String? articleId) =>
      super.noSuchMethod(
        Invocation.method(#removeArticleFromGoal, [goalId, articleId]),
        returnValueForMissingStub: null,
      );

  @override
  void updateArticleInGoal(String? goalId, _i4.Article? updatedArticle) =>
      super.noSuchMethod(
        Invocation.method(#updateArticleInGoal, [goalId, updatedArticle]),
        returnValueForMissingStub: null,
      );
}
